namespace OrganizingCSharpCode;
// Write your answer here, and then test your code.
// Your job is to use a dynamic type with a known 
// method, GenerateAnswer, to complete the operation
public class Answer
{
    // Change these Boolean values to control whether you see 
    // the expected result and/or hints.
    public  static Boolean ShowExpectedResult = false;
    public  static Boolean ShowHints = false;

    // Return the answer generated by the answerGenerator when passed
    // the number parameter.
    public static int GetAnswer(object answerGenerator, int number) {
        // Your code goes here.

        return 0;
    } 
}